### ISSUE TITLE
Checks [HANDLER]

### ISSUE THREAD

**Issue by wDiogolo** [Dannyiy/sadinvader#3]
This shit doesn't work

**Comment by Dannyiy** [comment]
**More details would be really appreciated.**

**Comment by Dannyiy** [comment]
Some improvements will be applied to the checks system when it will be patched

**Comment by wDiogolo** [comment]
Details in your ass

**Comment by Dannyiy** [comment]
Patched: See commit https://github.com/Dannyiy/sadinvader/commit/8917166bfa267750a2a08d99d4ed13a9323a0960
